services:
  postgres:
    image: postgres:latest
    container_name: finance
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance-db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

volumes:
  .postgres-db:
